# === Required Variables ===
LAMA_PATH ?= $(shell pwd)/../Lama
LAMAC ?= $(LAMA_PATH)/src/lamac
RUNTIME_DIR := $(LAMA_PATH)/runtime
STD_LIB_DIR := $(LAMA_PATH)/stdlib/x64
BUILD_DIR := build
DUMP_DIR := dump

# Export them globally
export LAMA_PATH
export LAMAC
export RUNTIME_DIR
export STD_LIB_DIR

# === Targets ===
.PHONY: help deps build run clean

help:
	@echo "Usage: make run FILE=<name>.bs"
	@echo "Required env variables: LAMA_PATH=<path-to-lama-src> LAMAC=<path-to-lamac>"
	@echo "  dump FILE=<name>.lama      Compile .lama file to stack machine code (.sm) and move to ./dump/"
	@echo "  build                      Build LamaRpreter with Zig and copy to ./build/"
	@echo "  run FILE=<name>.bs         Run the compiled .bs file with LamaRpreter"
	@echo "  clean                      Remove build and dump directories"

# === 1. dump ===
dump:
	@if [ -z "$(FILE)" ]; then \
        echo "Error: FILE=<name>.lama is required"; \
        exit 1; \
    fi
	@echo "Compiling $(FILE) to stack code..."
	@$(LAMAC) -64 "$(FILE)" -I "$(STD_LIB_DIR)" -runtime "$(RUNTIME_DIR)" -ds
	@# Extract base name without extension
	@BASENAME=$$(basename "$(FILE)" .lama)
	@# Move .sm file to dump folder
	@mkdir -p "$(DUMP_DIR)"
	@mv "$$(basename "$(FILE)" .lama).sm" "$(DUMP_DIR)/" || echo "No .sm file found to move"
	@rm "$$(basename "$(FILE)" .lama).s"
	@rm "$$(basename "$(FILE)" .lama).i"
	@rm "$$(basename "$(FILE)" .lama)"
	@echo "Stack code dumped to $(DUMP_DIR)/$$(basename "$(FILE)" .lama).sm"

hex:
	@if [ -z "$(FILE)" ]; then \
        echo "Error: FILE=<name>.lama is required"; \
        exit 1; \
    fi
	@echo "Compiling $(FILE) to stack code..."
	@$(LAMAC) -64 "$(FILE)" -I "$(STD_LIB_DIR)" -runtime "$(RUNTIME_DIR)" -b
	@BASENAME=$$(basename "$(FILE)" .lama)
	@mkdir -p "$(DUMP_DIR)"
	@mv "$$(basename "$(FILE)" .lama).bc" "$(DUMP_DIR)/" || echo "No .sm file found to move"
	@echo "Bytecode dumped to $(DUMP_DIR)/$$(basename "$(FILE)" .lama).bc"

# === 2. build ===
build:
	@echo "Building LamaRpreter with Zig..."
	@zig build
	@mkdir -p "$(BUILD_DIR)"
	@cp zig-out/bin/LamaRpreter "$(BUILD_DIR)/"
	@echo "LamaRpreter copied to $(BUILD_DIR)/"

# === 3. run ===
run: build
	@if [ -z "$(FILE)" ]; then \
        echo "Error: FILE=<name>.bs is required"; \
        exit 1; \
    fi
	@echo "Running LamaRpreter on $(FILE)..."
	@$(BUILD_DIR)/LamaRpreter --parse-only "$(FILE)"

test: build
	@echo "Running tests..."
	@zig build test --summary all

# === 7. test-lama ===
test-lama: build
	@echo "🔍 Running all .lama files in test-lama/ via hex + run..."
	@mkdir -p "$(DUMP_DIR)"
	@# Find all .lama files in test-lama/
	@for file in test-lama/*.lama; do \
        if [ ! -f "$$file" ]; then \
            echo "No .lama files found in test-lama/"; \
            exit 0; \
        fi; \
        echo "🧪 Processing: $$file"; \
        BASENAME=$$(basename "$$file" .lama); \
        make hex FILE="$$file"; \
        if [ -f "$(DUMP_DIR)/$$BASENAME.bc" ]; then \
            echo "✅ Generated bytecode: $(DUMP_DIR)/$$BASENAME.bc"; \
            make run FILE="$(DUMP_DIR)/$$BASENAME.bc"; \
        else \
            echo "❌ Failed to generate .bc for $$file"; \
        fi; \
    done
	@echo "✅ All tests in test-lama/ completed."

# === 4. clean ===
clean:
	@echo "Cleaning build and dump directories..."
	@rm -rf "$(BUILD_DIR)"
	@rm -rf "$(DUMP_DIR)"
	@echo "Done."

# === Default target ===
.PHONY: all
all: help
